export interface TimeZoneInfo {
  id: string;
  label: string;
  region: string;
}

export const TIMEZONES: TimeZoneInfo[] = [
  { id: 'UTC', label: 'UTC', region: 'Universal' },
  { id: 'America/New_York', label: 'New York', region: 'Americas' },
  { id: 'America/Los_Angeles', label: 'Los Angeles', region: 'Americas' },
  { id: 'America/Chicago', label: 'Chicago', region: 'Americas' },
  { id: 'America/Denver', label: 'Denver', region: 'Americas' },
  { id: 'America/Toronto', label: 'Toronto', region: 'Americas' },
  { id: 'America/Vancouver', label: 'Vancouver', region: 'Americas' },
  { id: 'America/Mexico_City', label: 'Mexico City', region: 'Americas' },
  { id: 'America/Sao_Paulo', label: 'São Paulo', region: 'Americas' },
  { id: 'America/Buenos_Aires', label: 'Buenos Aires', region: 'Americas' },
  { id: 'Europe/London', label: 'London', region: 'Europe' },
  { id: 'Europe/Paris', label: 'Paris', region: 'Europe' },
  { id: 'Europe/Berlin', label: 'Berlin', region: 'Europe' },
  { id: 'Europe/Rome', label: 'Rome', region: 'Europe' },
  { id: 'Europe/Madrid', label: 'Madrid', region: 'Europe' },
  { id: 'Europe/Amsterdam', label: 'Amsterdam', region: 'Europe' },
  { id: 'Europe/Brussels', label: 'Brussels', region: 'Europe' },
  { id: 'Europe/Vienna', label: 'Vienna', region: 'Europe' },
  { id: 'Europe/Stockholm', label: 'Stockholm', region: 'Europe' },
  { id: 'Europe/Copenhagen', label: 'Copenhagen', region: 'Europe' },
  { id: 'Europe/Oslo', label: 'Oslo', region: 'Europe' },
  { id: 'Europe/Helsinki', label: 'Helsinki', region: 'Europe' },
  { id: 'Europe/Warsaw', label: 'Warsaw', region: 'Europe' },
  { id: 'Europe/Prague', label: 'Prague', region: 'Europe' },
  { id: 'Europe/Budapest', label: 'Budapest', region: 'Europe' },
  { id: 'Europe/Athens', label: 'Athens', region: 'Europe' },
  { id: 'Europe/Istanbul', label: 'Istanbul', region: 'Europe' },
  { id: 'Europe/Moscow', label: 'Moscow', region: 'Europe' },
  { id: 'Asia/Dubai', label: 'Dubai', region: 'Asia' },
  { id: 'Asia/Kolkata', label: 'Mumbai', region: 'Asia' },
  { id: 'Asia/Singapore', label: 'Singapore', region: 'Asia' },
  { id: 'Asia/Tokyo', label: 'Tokyo', region: 'Asia' },
  { id: 'Asia/Hong_Kong', label: 'Hong Kong', region: 'Asia' },
  { id: 'Asia/Shanghai', label: 'Shanghai', region: 'Asia' },
  { id: 'Asia/Seoul', label: 'Seoul', region: 'Asia' },
  { id: 'Asia/Bangkok', label: 'Bangkok', region: 'Asia' },
  { id: 'Asia/Jakarta', label: 'Jakarta', region: 'Asia' },
  { id: 'Asia/Manila', label: 'Manila', region: 'Asia' },
  { id: 'Asia/Taipei', label: 'Taipei', region: 'Asia' },
  { id: 'Asia/Kuala_Lumpur', label: 'Kuala Lumpur', region: 'Asia' },
  { id: 'Asia/Karachi', label: 'Karachi', region: 'Asia' },
  { id: 'Asia/Tehran', label: 'Tehran', region: 'Asia' },
  { id: 'Asia/Jerusalem', label: 'Jerusalem', region: 'Asia' },
  { id: 'Australia/Sydney', label: 'Sydney', region: 'Oceania' },
  { id: 'Australia/Melbourne', label: 'Melbourne', region: 'Oceania' },
  { id: 'Australia/Brisbane', label: 'Brisbane', region: 'Oceania' },
  { id: 'Australia/Perth', label: 'Perth', region: 'Oceania' },
  { id: 'Pacific/Auckland', label: 'Auckland', region: 'Oceania' },
  { id: 'Pacific/Fiji', label: 'Fiji', region: 'Oceania' },
  { id: 'Pacific/Honolulu', label: 'Honolulu', region: 'Oceania' },
  { id: 'Africa/Cairo', label: 'Cairo', region: 'Africa' },
  { id: 'Africa/Johannesburg', label: 'Johannesburg', region: 'Africa' },
  { id: 'Africa/Lagos', label: 'Lagos', region: 'Africa' },
  { id: 'Africa/Nairobi', label: 'Nairobi', region: 'Africa' },
  { id: 'Africa/Casablanca', label: 'Casablanca', region: 'Africa' }
];
